fix: update action dependencies
checkout@6 broke runs with create-pull-requests:

remote: Duplicate header: "Authorization"
fatal: unable to access 'https://github.com/gepbird/nur-packages/': The requested URL returned error: 400
Error: The process '/usr/bin/git' failed with exit code 128

This was fixed in create-pull-request@7.0.9.